[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "npm run build"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyMaxRetries = 10
restartPolicyType = "ON_FAILURE"
startCommand = "npm run start"
